> # Tensorflow Datatype #

Tensorflow is a library for numerical calculation. Tensorflow API circulates tensor. A tensor flows from one calcute to other calculate. Tensor is simillar to numpy **ndarray**. So tensor can get n-dimension. It is important to make custom loss fuction, layer, index and etc.

**tf.constant()** makes a tensor.

In [1]:
import numpy as np
import tensorflow as tf

### - Constant Tensor ###

In [2]:
tf.constant([[1.,2.,3.],[4.,5.,6.]])  #2x3 matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(1.)   #scalar

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

Like **ndarray**, tensor has shape and dtype.

In [4]:
tsr = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(tsr.shape)
print(tsr.dtype)

(2, 3)
<dtype: 'float32'>


Indexing is also operated like numpy.

In [5]:
tsr[:, :1]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [4.]], dtype=float32)>

In [6]:
tsr[:,1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

All kinds of tensor operation are available.

In [7]:
print(tsr+10)
print(tf.square(tsr))
print(tsr @ tf.transpose(tsr))  # @ is dot operation

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


Tensorflow provides all basic math operation and most operation in numpy. But some fuctions have difference names(**tf.reduce_mean, tf.reduce_sum, tf.reduce_max, tf.math.log** is same with **np.mean, np.sum, np.max, np.log**). For example, in tensorflow, we have to use **tf.transpose(tsr)** not **tsr.T**. The season is the function of tensorflow doesn't operate completely same with numpy T. New tensor is made by copy of transposed data. But numpy function is transposed view of same data.

Tensor is convenient to use with numpy.

In [8]:
a = np.array([1, 3, 4])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4])>

In [9]:
tsr.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [10]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1,  9, 16])>

In [11]:
np.square(tsr)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

Type conversion can highly decreases performance. To prevent it, tensorflow doesn't automatically perform any type conversion. We can't operate float with integer and 32-float with 64-float. If we need conversion, use **cast** function.

In [12]:
tf.constant(2.) + tf.constant(42)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [14]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [15]:
t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### - Variable Tensor ###

Above tensor is immutable data. We can't change contents of tensor. So we can't realize weights of neural network which have to be changed by backpropagation. This is why **tf.Variable** is needed.

In [16]:
v = tf.Variable([[1., 2., 3.],[4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Its operation is similar with tensor. But we can change variable using **assign** method.

In [17]:
print(v.assign(2*v))
print(v[0,1].assign(3))
print(v[:,2].assign([0,1]))
print(v.scatter_nd_update(indices=[[0,0],[1,2]], updates=[100,200]))

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  3.,  6.],
       [ 8., 10., 12.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  3.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   3.,   0.],
       [  8.,  10., 200.]], dtype=float32)>
